modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/simply-kel/simplystatus/issues"
license="MIT"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "simplystatus"
version = "${version}"
displayURL = "https://modrinth.com/mod/simplystatus"
displayName = "SimplyStatus"
updateJSONURL = "https://api.modrinth.com/updates/simplystatus/forge_updates.json"
authors = "Kel Cuprum"
credits = "Deflecta (Russian Localization), GRUI_72 (Good ideas)"
description = "Simple, customizable Discord game status"
logoFile = "assets/simplystatus/logo.png"

[[dependencies.simplystatus]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplystatus]]
modId = "alinlib"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplystatus]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"